//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentSection_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommentSection_Table()
        {
            this.LikeComment_Table = new HashSet<LikeComment_Table>();
        }
    
        public int CommentID { get; set; }
        public int RecipeID { get; set; }
        public int CommentFloor { get; set; }
        public int MemberID { get; set; }
        public string Comment { get; set; }
        public byte[] Picture { get; set; }
        public string Video { get; set; }
        public System.DateTime PostTime { get; set; }
        public bool DisVisible { get; set; }
        public bool DeleteOrNot { get; set; }
    
        public virtual Member_Table Member_Table { get; set; }
        public virtual Recipe_Table Recipe_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LikeComment_Table> LikeComment_Table { get; set; }
    }
}
