//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeliciousEntities : DbContext
    {
        public DeliciousEntities()
            : base("name=DeliciousEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accusation_Table> Accusation_Table { get; set; }
        public virtual DbSet<AccuseContent_Table> AccuseContent_Table { get; set; }
        public virtual DbSet<Admin_Table> Admin_Table { get; set; }
        public virtual DbSet<Authority_Table> Authority_Table { get; set; }
        public virtual DbSet<Collection_Table> Collection_Table { get; set; }
        public virtual DbSet<CollectionFolder_Table> CollectionFolder_Table { get; set; }
        public virtual DbSet<CommentSection_Table> CommentSection_Table { get; set; }
        public virtual DbSet<Feedback_Category_Table> Feedback_Category_Table { get; set; }
        public virtual DbSet<Feedback_Progress_Table> Feedback_Progress_Table { get; set; }
        public virtual DbSet<Feedback_Table> Feedback_Table { get; set; }
        public virtual DbSet<Hashtag_Record_Table> Hashtag_Record_Table { get; set; }
        public virtual DbSet<Hashtag_Table> Hashtag_Table { get; set; }
        public virtual DbSet<Ingredient_Record_Table> Ingredient_Record_Table { get; set; }
        public virtual DbSet<Ingredient_Table> Ingredient_Table { get; set; }
        public virtual DbSet<IngredientCategory_Table> IngredientCategory_Table { get; set; }
        public virtual DbSet<LikeComment_Table> LikeComment_Table { get; set; }
        public virtual DbSet<LikeRecipe_Table> LikeRecipe_Table { get; set; }
        public virtual DbSet<Member_Rank_Table> Member_Rank_Table { get; set; }
        public virtual DbSet<Member_Table> Member_Table { get; set; }
        public virtual DbSet<Merchandise_Picture_Table> Merchandise_Picture_Table { get; set; }
        public virtual DbSet<Order_Detail_Table> Order_Detail_Table { get; set; }
        public virtual DbSet<Order_Table> Order_Table { get; set; }
        public virtual DbSet<Recipe_Table> Recipe_Table { get; set; }
        public virtual DbSet<RecipeCategory_Table> RecipeCategory_Table { get; set; }
        public virtual DbSet<Shopping_Cart_table> Shopping_Cart_table { get; set; }
        public virtual DbSet<Steps_Table> Steps_Table { get; set; }
        public virtual DbSet<Wish_List_Table> Wish_List_Table { get; set; }
    }
}
