//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member_Table()
        {
            this.Accusation_Table = new HashSet<Accusation_Table>();
            this.CollectionFolder_Table = new HashSet<CollectionFolder_Table>();
            this.CommentSection_Table = new HashSet<CommentSection_Table>();
            this.Feedback_Table = new HashSet<Feedback_Table>();
            this.LikeComment_Table = new HashSet<LikeComment_Table>();
            this.LikeRecipe_Table = new HashSet<LikeRecipe_Table>();
            this.Order_Table = new HashSet<Order_Table>();
            this.Recipe_Table = new HashSet<Recipe_Table>();
            this.Shopping_Cart_table = new HashSet<Shopping_Cart_table>();
            this.Wish_List_Table = new HashSet<Wish_List_Table>();
        }
    
        public int MemberID { get; set; }
        public string AccountName { get; set; }
        public string Nickname { get; set; }
        public string MemberName { get; set; }
        public string CellNumber { get; set; }
        public string CellConfirm { get; set; }
        public string Email { get; set; }
        public System.Guid EmailConfirm { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Gender { get; set; }
        public string Info { get; set; }
        public bool ConfirmedOrNot_email { get; set; }
        public bool ConfirmedOrNot_phone { get; set; }
        public string Password { get; set; }
        public System.DateTime RegisterTime { get; set; }
        public int PersonalRankScore { get; set; }
        public int RankID { get; set; }
        public int AuthorityID { get; set; }
        public string Figure { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accusation_Table> Accusation_Table { get; set; }
        public virtual Authority_Table Authority_Table { get; set; }
        public virtual Authority_Table Authority_Table1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectionFolder_Table> CollectionFolder_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentSection_Table> CommentSection_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback_Table> Feedback_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LikeComment_Table> LikeComment_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LikeRecipe_Table> LikeRecipe_Table { get; set; }
        public virtual Member_Rank_Table Member_Rank_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Table> Order_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recipe_Table> Recipe_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shopping_Cart_table> Shopping_Cart_table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wish_List_Table> Wish_List_Table { get; set; }
    }
}
