//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Detail_Table
    {
        public int Order_DetailID { get; set; }
        public int OrderiD { get; set; }
        public int IngredientID { get; set; }
        public decimal Price { get; set; }
        public double Discount { get; set; }
        public int InCartQuantity { get; set; }
    
        public virtual Ingredient_Table Ingredient_Table { get; set; }
        public virtual Order_Table Order_Table { get; set; }
    }
}
