//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace customerChatServer.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_Table()
        {
            this.Order_Detail_Table = new HashSet<Order_Detail_Table>();
        }
    
        public int OrderID { get; set; }
        public int MemberID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string DeliveryAddress { get; set; }
        public string PayMethod { get; set; }
    
        public virtual Member_Table Member_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Detail_Table> Order_Detail_Table { get; set; }
    }
}
